language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - APP_KEY=jCGotmYwQYTf9w9qBwQrVuV8OKQ5gyQF

install:
  - touch tests/test.sqlite
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit